<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs" version="2.0">

    <!-- Last Updated: November 13, 2021 -->

    <!-- Configure the transformation with empty.xml as source.
            The path of files to be combined changes with each batch.
                In Windows, use this: file:///file:///C://Users/
                In OSX, use this: //Users/       
                Example:
                <xsl:copy-of select="document('//Users/Volumes/Groups/CS/TechResources/Bepress-migration/Source_Data/etds/bepress_metadata/unsup-etd_metadata/bepress_UTF8/bepress_all_uft8/etd-0994.metadata.xml')"/>
                
                <xsl:copy-of select="document('//Users/annie/Volumes/Groups/CS/TechResources/ETDs/ProQuest_files/2017C_fall/DATA/Acar_fsu_0071E_14749_DATA.xml')"/>
                
                <xsl:copy-of
                select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2020/2020_BC_summer_fall/DATA/Abdullah_fsu_0071E_16363_DATA.xml')"/>
        -->

    <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
    <xsl:strip-space elements="*"/>

    <xsl:template match="xml">
        <xml>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Abel_fsu_0071N_17212_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Aderibigbe_fsu_0071E_16940_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Adkins_fsu_0071E_17168_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Agastra_fsu_0071N_17219_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Ahn_fsu_0071E_16992_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Altenhof_fsu_0071E_16945_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Anderson_fsu_0071E_17155_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Atkins_fsu_0071E_17006_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Bagdy_fsu_0071E_17154_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Bagneris_fsu_0071E_17238_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Barnes_fsu_0071E_16950_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Barnes_fsu_0071N_17032_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Beery_fsu_0071E_17035_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Behl_fsu_0071E_17060_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Behnke_fsu_0071E_16943_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Berlin_fsu_0071N_17235_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Betancourt_fsu_0071E_17016_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Betz_fsu_0071N_17170_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Bierson_fsu_0071E_17099_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Binoy_fsu_0071E_17152_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Boyun_fsu_0071N_17009_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Brewster_fsu_0071E_17067_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Brimhall_fsu_0071N_17190_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Brown_fsu_0071E_16959_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Brown_fsu_0071N_17002_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Burnett_fsu_0071N_17211_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Cai_fsu_0071N_16997_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Callahan_fsu_0071E_17147_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Cantrill_fsu_0071N_17186_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Carlisle_fsu_0071E_16960_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Carrara_fsu_0071E_16994_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Chaaban_fsu_0071E_17017_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Chancy_fsu_0071E_16966_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Chandler_fsu_0071N_17194_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Chatmon_fsu_0071E_17021_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Chen_fsu_0071E_16972_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Chen_fsu_0071E_17050_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Chen_fsu_0071E_17101_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Clark_fsu_0071E_17094_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Clark_fsu_0071E_17095_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Cohen_fsu_0071N_17201_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Cole_fsu_0071N_17079_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Conti_fsu_0071E_17033_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Copeland_fsu_0071E_17149_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Cortelletti_fsu_0071N_17216_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Creighton_fsu_0071N_17187_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Crook_fsu_0071E_17162_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Denecke_fsu_0071E_17066_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Dillard_fsu_0071E_16949_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Duke_fsu_0071E_17143_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Edwards_fsu_0071E_17077_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Edwards_fsu_0071E_17112_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Fairclough_fsu_0071E_17075_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Farley_fsu_0071E_16993_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Feng_fsu_0071E_17158_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Ferguson_fsu_0071E_17013_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Forde_fsu_0071E_17031_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Fumero_fsu_0071E_16995_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Garceau_fsu_0071E_17063_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Garinger_fsu_0071E_16999_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Gaye_fsu_0071N_17111_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Geerlings_fsu_0071E_17015_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/George_fsu_0071E_17119_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Gibbs_fsu_0071N_17220_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Gladwin_fsu_0071E_16965_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Glennie_fsu_0071E_17018_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Goldstein_fsu_0071E_17000_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Graham_fsu_0071E_16944_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Green_fsu_0071E_16955_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Griffin_fsu_0071E_16983_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hamilton_fsu_0071N_17048_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Han_fsu_0071E_17128_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hansen_fsu_0071E_17084_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Harry_fsu_0071E_17030_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hatcher_fsu_0071E_16947_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Helsper_fsu_0071E_16872_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hernandez_fsu_0071E_16963_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hilton_fsu_0071E_16942_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/HOSSAIN_fsu_0071E_17130_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/HU_fsu_0071E_17122_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Huang_fsu_0071E_16876_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hughes_fsu_0071E_17047_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hunkapiller_fsu_0071E_17137_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Hurley_fsu_0071E_17097_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Iguchi_fsu_0071E_16981_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Irving_fsu_0071N_16952_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/IsernMas_fsu_0071N_17196_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Jackson_fsu_0071E_17012_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Jiang_fsu_0071E_17115_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Jing_fsu_0071E_17108_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Johnson_fsu_0071E_17109_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Johnson_fsu_0071N_17214_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Johnston_fsu_0071E_17078_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Jolowsky_fsu_0071E_17118_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Karaer_fsu_0071E_17051_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Kelly_fsu_0071E_17145_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Khamitova_fsu_0071E_17135_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Kierspe_fsu_0071E_17104_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Kim_fsu_0071E_17090_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Kozik_fsu_0071E_17123_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Kudelka_fsu_0071N_17176_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/KURIAKOSE_fsu_0071E_17131_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Kuzel_fsu_0071N_17188_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Kviatkovsky_fsu_0071E_17165_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lamb_fsu_0071E_16853_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lanaghan_fsu_0071N_17246_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/LandiConde_fsu_0071N_17184_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Law_fsu_0071E_17098_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Law_fsu_0071N_17179_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/LeBlanc_fsu_0071E_16977_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lian_fsu_0071E_16898_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lipham_fsu_0071N_17072_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Liu_fsu_0071E_17029_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lizotte_fsu_0071N_17217_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Long_fsu_0071E_16969_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Longley_fsu_0071E_17230_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lord_fsu_0071E_17117_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Louis_fsu_0071N_17261_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lteif_fsu_0071E_17024_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lundstrom_fsu_0071N_17207_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Luttig_fsu_0071E_16953_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Lyles_fsu_0071N_17198_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Ma_fsu_0071E_17096_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/MacFarlane_fsu_0071E_17052_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Mack_fsu_0071N_17195_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/MackinnonGreenwalt_fsu_0071N_17172_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Maillet_fsu_0071E_16996_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Mao_fsu_0071E_17011_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Marcous_fsu_0071E_17234_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/MarinVelasquez_fsu_0071E_17150_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Marshall_fsu_0071E_17003_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Masek_fsu_0071E_16984_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/May_fsu_0071E_17004_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/McCown_fsu_0071E_17126_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/McFarland_fsu_0071E_17134_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/McQueen_fsu_0071E_16970_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/MedinaFarias_fsu_0071E_17093_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Mehra_fsu_0071N_17178_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Mendez_fsu_0071E_17040_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Meng_fsu_0071E_17086_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Mersiovsky_fsu_0071N_17025_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/MetzgerPeiskee_fsu_0071E_17114_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Meyer_fsu_0071N_17042_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Michel_fsu_0071N_17023_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Min_fsu_0071E_17074_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Moore_fsu_0071E_16956_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Moore_fsu_0071E_17037_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Morabito_fsu_0071N_17174_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Morton_fsu_0071N_17203_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Mosley_fsu_0071E_16987_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Mou_fsu_0071E_17175_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Murdock_fsu_0071E_17148_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Myers_fsu_0071N_17189_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Naser_fsu_0071E_17091_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/NatarajBhargav_fsu_0071E_17027_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Olivett_fsu_0071N_17204_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Orris_fsu_0071E_17054_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Owen_fsu_0071E_17151_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Paquette_fsu_0071E_16990_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Park_fsu_0071N_17177_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Parker_fsu_0071E_17059_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Patel_fsu_0071E_17044_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Pelham_fsu_0071E_17005_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/PERKINS_fsu_0071N_17202_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Pitts_fsu_0071N_17208_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Prado_fsu_0071N_17205_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Propper_fsu_0071E_17057_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Pruitt_fsu_0071E_17107_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Qi_fsu_0071N_17181_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Rassolov_fsu_0071E_17138_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Reed_fsu_0071E_17064_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Reed_fsu_0071E_17076_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Rene_fsu_0071E_17082_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Rizza_fsu_0071E_17056_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Roache_fsu_0071E_17160_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Robb_fsu_0071E_17159_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Robbins_fsu_0071E_17132_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Rocker_fsu_0071E_17105_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/RODRIGUEZ_fsu_0071E_16976_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Rosario_fsu_0071E_16901_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Rosenberger_fsu_0071E_16937_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Roy_fsu_0071E_16980_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Ruechel_fsu_0071E_17028_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Ruff_fsu_0071E_17113_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Rushing_fsu_0071N_17053_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Russell_fsu_0071E_17020_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sadguna_fsu_0071E_16998_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Santos_fsu_0071E_17041_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sanusi_fsu_0071E_17156_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Saunders_fsu_0071E_17036_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Savedge_fsu_0071N_17206_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sebeny_fsu_0071E_17139_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Seigler_fsu_0071N_17263_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Shafer_fsu_0071E_17019_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Shen_fsu_0071E_16860_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sherrod_fsu_0071N_17039_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Shi_fsu_0071E_16991_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Siegler_fsu_0071E_17153_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Simeon_fsu_0071N_17222_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Smith_fsu_0071E_16883_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Smith_fsu_0071E_17100_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Snowden_fsu_0071E_16979_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sogluizzo_fsu_0071N_17124_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sorenson_fsu_0071E_17227_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sprague_fsu_0071N_17224_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Stanisauskis_fsu_0071E_16951_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Stevens_fsu_0071N_16975_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Stewart_fsu_0071E_17022_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Su_fsu_0071E_17061_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sullenberger_fsu_0071E_17157_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Sun_fsu_0071E_16988_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Taondeyande_fsu_0071N_17275_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Thames_fsu_0071E_16941_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Thomas_fsu_0071E_17071_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Thomasee_fsu_0071E_16971_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Thompson_fsu_0071E_17092_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/ThompsonPlunkett_fsu_0071E_16962_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Tillet_fsu_0071E_17103_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Tobias_fsu_0071E_16978_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Tommasone_fsu_0071N_17199_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Tsang_fsu_0071E_17073_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Varga_fsu_0071E_17010_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Verity_fsu_0071E_17070_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Waddell_fsu_0071N_17215_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Walsh_fsu_0071N_17043_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/WANG_fsu_0071E_16875_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Wang_fsu_0071E_16968_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Wang_fsu_0071E_17007_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Wang_fsu_0071E_17058_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Wang_fsu_0071E_17127_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Warnick_fsu_0071N_17236_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/West_fsu_0071E_17141_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Westervelt_fsu_0071E_17140_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Westman_fsu_0071N_17242_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Wilhelmy_fsu_0071N_17213_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Wilkins_fsu_0071E_17200_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Williams_fsu_0071E_17243_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Willmann_fsu_0071E_17081_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Wu_fsu_0071E_16823_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/You_fsu_0071E_17080_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Zeng_fsu_0071E_16958_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Zhang_fsu_0071E_16946_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/zheng_fsu_0071E_16974_DATA.xml')"/>
            <xsl:copy-of select="document('file:///C:/Users/achisum.FSU/OneDrive - Florida State University/Desktop/Project_Files/ETDs/ETD_MODS/2022/2022A_spring/DATA/Zhou_fsu_0071E_17163_DATA.xml')"/>
        </xml>
    </xsl:template>

</xsl:stylesheet>
